name: build & deploy

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM install 📦
        uses: bahmutov/npm-install@v1

      - name: Build site 🏗
        run: npm run docs:build

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs/.vuepress/dist

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
  
    - name: Install and Build
      run: |
        npm install
        npm run build
        
    - name: Deploy Build Files
      env:
        # You should enroll ACEESS_TOKEN to repository's secret
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      run: |
        cd docs/.vuepress/dist
        git config --global user.email "throw@cttd.co.kr"
        git config --global user.name "bottlemen"
        git init
        git add -A
        git commit -m 'deploy with vuepress'
        git push -f https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages
